exports.studentsListPage = function(list, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="/static/favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Students List
                    <a class="w3-btn w3-round w3-grey" href="/alunos/registo">+</a>
                    </h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>GitHub</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < list.length ; i++){
        pagHTML += `
                <tr>
                    <td>${list[i].id}</td>
                    <td>
                         <a href="/alunos/${list[i].id}" class="w3-text-pale-blue">${list[i].nome}</a>
                    </td>
                    <td>
                        <a href="${list[i].git}" target="_blank" class="w3-text-pale-green">${list[i].git}</a>
                    </td>
                    <td>
                        <a href="/alunos/edit/${list[i].id}" class="w3-button w3-green w3-small">Edit</a>
                        <a href="/alunos/delete/${list[i].id}" class="w3-button w3-red w3-small">Remove</a>
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by PP_ENGWEB2025 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.studentFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="/static/favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Students Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-grey">
                    <h2>Students Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Student Info</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="git"/>
                    </fieldset>

                    <fieldset>
                        <legend>TPCs</legend>
                        <input class="w3-check" type="checkbox" name="tpc1" value="1"/>
                        <label>TPC1</label>
                        <input class="w3-check" type="checkbox" name="tpc2" value="1"/>
                        <label>TPC2</label>
                        <input class="w3-check" type="checkbox" name="tpc3" value="1"/>
                        <label>TPC3</label>
                        <input class="w3-check" type="checkbox" name="tpc4" value="1"/>
                        <label>TPC4</label>
                        <input class="w3-check" type="checkbox" name="tpc5" value="1"/>
                        <label>TPC5</label>
                        <input class="w3-check" type="checkbox" name="tpc6" value="1"/>
                        <label>TPC6</label>
                        <input class="w3-check" type="checkbox" name="tpc7" value="1"/>
                        <label>TPC7</label>
                        <input class="w3-check" type="checkbox" name="tpc8" value="1"/>
                        <label>TPC8</label>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-blue">
                    <h5>Generated by PP_ENGWEB2025 in ${d}</h5>
                </footer>
            
            </div>
    `
}

exports.studentFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="/static/favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Students Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h2>Students Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Students Info</legend>
                            <legend class="w3-text-black"><b>Informações do Estudante</b></legend>
                            <label><b>ID</b></label>
                            <input class="w3-input w3-border w3-round" type="text" name="id" readonly value="${a.id}"/>
                            
                            <label><b>Nome</b></label>
                            <input class="w3-input w3-border w3-round" type="text" name="nome" value="${a.nome}"/>
                            
                            <label><b>GitHub</b></label>
                            <input class="w3-input w3-border w3-round" type="text" name="git" value="${a.git}"/>
                    </fieldset>

                    <fieldset>
                        <legend>TPC</legend>
                    `

    for (let i = 1; i <= 8; i++) {
        let tpc = "tpc" + i;
        let checked = Object.prototype.hasOwnProperty.call(a, tpc) ? "checked" : "";

        if (i === 1 || i === 5) pagHTML += `<div class="w3-half">`;

        pagHTML += `
            <input class="w3-check" type="checkbox" name="tpc${i}" value="1" ${checked}/>
            <label>TPC${i}</label><br/>
        `;

        if (i === 4 || i === 8) pagHTML += `</div>`;
    }          

    pagHTML += `
                    </fieldset>  
                    <br/>
                            <button class="w3-button w3-green w3-round w3-large w3-margin-top" type="submit">
                                Submit
                            </button>
                    </form>                

                <footer class="w3-container w3-blue">
                    <h5>Generated by PP_ENGWEB2025 in ${d}</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.studentPage = function( aluno, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Student: ${aluno.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Aluno ${aluno.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${aluno.nome}</li>
                    <li><b>Número: </b> ${aluno.id}</li>
                    <li><b>GitHub: </b> <a href="${aluno.git}">${aluno.git}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            for(let i=1; i < 9; i++){
                key = `tpc${i}`
                if(key in aluno){
                    pagHTML += `
                        <li><b>TPC${i}</b></li>
                    `
                }
            }
    

    pagHTML +=     `</ul></div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by PP_ENGWEB2025 in ${d}</h5>
                </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}